<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputsignInSubmit</name>
   <tag></tag>
   <elementGuidId>a9268b55-292a-4603-974f-b3020cf71064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>541277b1-8033-46c5-9c34-62e92e6c9568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInSubmit</value>
      <webElementGuid>8c6cab8f-74b7-427c-b0e3-064dc4baa5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>cab7934a-78fa-4f7c-bd64-e070cba959a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>2a6c085f-854b-4bfe-824e-7883cd848566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>db82b76a-1c73-4228-819d-04a501896f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>auth-signin-button-announce</value>
      <webElementGuid>3dc3cd99-49ba-4d12-830a-6e68a6474cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInSubmit&quot;)</value>
      <webElementGuid>a3c75133-c7b1-44f9-a849-cf4acda2ff2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInSubmit']</value>
      <webElementGuid>023444c0-3eed-40d4-a2f1-b3c32476170d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='auth-signin-button']/span/input</value>
      <webElementGuid>9589f1e9-7dca-46b7-82ef-9e4a8367d8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>787c0fd2-9f3c-46a7-b39d-53c0b528031b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signInSubmit' and @type = 'submit']</value>
      <webElementGuid>59de2b70-861b-41cc-8fd4-21b01d5c8676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
