<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_s-product-image-container aok-relative _be1407</name>
   <tag></tag>
   <elementGuidId>69f62ef0-52df-4cfd-a7f8-bec01cc6faff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/span/div/div/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.s-product-image-container.aok-relative.s-image-overlay-grey.s-text-center.s-expand-height.s-list-image-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>725bff22-904b-4eb5-b9d9-7e032ad37cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-product-image-container aok-relative s-image-overlay-grey s-text-center s-expand-height s-list-image-container</value>
      <webElementGuid>745a4922-81b7-4bd0-8785-60f54e868738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;s-desktop-width-max s-desktop-content s-wide-grid-style-t1 s-opposite-dir s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-20-of-24 s-matching-dir sg-col-16-of-20 sg-col sg-col-8-of-12 sg-col-12-of-16&quot;]/div[@class=&quot;sg-col-inner&quot;]/span[@class=&quot;rush-component s-latency-cf-section&quot;]/div[@class=&quot;s-main-slot s-result-list s-search-results sg-row&quot;]/div[@class=&quot;a-section a-spacing-none s-result-item s-flex-full-width s-widget s-widget-spacing-large&quot;]/div[@class=&quot;s-widget-container s-spacing-medium s-widget-container-height-medium celwidget slot=MAIN template=ONE_SECTION widget=loom-desktop-top-slot_1c72f670-f242-42c0-b27f-7ad338386c06 pf_rd_p=0b14e96e-531f-4e53-91d3-b32bea3d9a78 pf_rd_r=N3GSB33CE6H2J7Q10J08 pd_rd_wg-cJJxP pd_rd_w-C9a5b content-id=amzn1.sym.0b14e96e-531f-4e53-91d3-b32bea3d9a78:amzn1.sym.0b14e96e-531f-4e53-91d3-b32bea3d9a78 pd_rd_r-e1781305-f647-4975-973e-e6bb3c09ae21 widgetId=loom-desktop-top-slot_1c72f670-f242-42c0-b27f-7ad338386c06&quot;]/div[@class=&quot;s-widget-background&quot;]/div[@class=&quot;s-card-container s-overflow-hidden aok-relative s-card-border&quot;]/div[@class=&quot;sg-row-align-items-center sg-row&quot;]/div[@class=&quot;sg-col-4-of-24 sg-col-4-of-12 sg-col-4-of-16 sg-col sg-col-4-of-20&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;a-section a-text-center s-expand-height&quot;]/div[@class=&quot;s-product-image-container aok-relative s-image-overlay-grey s-text-center s-expand-height s-list-image-container&quot;]</value>
      <webElementGuid>5416fcbe-86d0-48d0-9afa-2398d819356d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/span/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>d7380696-ec0d-4732-b28f-9c2113a561c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>51ce49ae-1769-4f02-bff4-1487429afb26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
