<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_apple macbook air</name>
   <tag></tag>
   <elementGuidId>45662049-0a92-4553-8c75-4c2af55192f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-color-state.a-text-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/span[2]/div/h1/div/div/div/div/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>63eb5004-dfa5-4837-9c9b-dbd9f3181b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-color-state a-text-bold</value>
      <webElementGuid>842bb5fc-a54b-485e-977b-9f0c45e635c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&quot;apple macbook air&quot;</value>
      <webElementGuid>644eb949-d8c8-4a10-bafb-7517d7d1f5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/span[@class=&quot;rush-component&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=UPPER template=RESULT_INFO_BAR widgetId=result-info-bar&quot;]/h1[@class=&quot;a-size-base s-desktop-toolbar a-text-normal&quot;]/div[@class=&quot;s-desktop-width-max sg-row-align-items-center s-wide-grid-style-t1 s-wide-grid-style sg-row&quot;]/div[@class=&quot;sg-col-14-of-20 sg-col-18-of-24 sg-col s-breadcrumb sg-col-10-of-16 sg-col-6-of-12&quot;]/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;a-section a-spacing-small a-spacing-top-small&quot;]/span[@class=&quot;a-color-state a-text-bold&quot;]</value>
      <webElementGuid>0e0ed72e-7917-4b70-8d64-b9573477405a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/span[2]/div/h1/div/div/div/div/span[3]</value>
      <webElementGuid>7c536687-18f5-452a-b1a6-f753a3784646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[3]</value>
      <webElementGuid>7c3a84da-cbfa-46bc-8386-30ad1f536b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '&quot;apple macbook air&quot;' or . = '&quot;apple macbook air&quot;')]</value>
      <webElementGuid>33c9576b-67ca-4052-997d-eb882e02390d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
