<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Not now</name>
   <tag></tag>
   <elementGuidId>4007d79f-07d7-44cf-9e54-9a9cde38ac9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ap-account-fixup-phone-skip-link']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ap-account-fixup-phone-skip-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7507b7dc-d779-4dfe-99c4-9884c3e07069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap-account-fixup-phone-skip-link</value>
      <webElementGuid>b011289c-c7c7-46bf-bbbc-5c3e0aecc641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>630345dc-31a5-4281-b987-aedc6eec010a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=XLvfZ7VC3EgHXkP4dIJ2Tj2BbyF1kj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_ya_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7Cax1j8TWvpt5B+nR5XQYnJTYJNOJu4tgl2mjSfMRaoY5ZjX%2FIzu6ZUl64qqjM08NKrKLv+tUYrtIiuSrQt3%2Fh+ZYIPa9c8TYpxtUNRU%2FANvlozPOkvu5FxVU+Sdhpv8P4AHOq3vCOxjxeh8GMeGf+BX2rjWiaUUD+Lk8Qg4USLT5rhqQlM9BXX8m4nKjSUB+7Fsd%2FPD7py%2FtXeUtT0G0yN5m6FROd+QGSsgj7HVNQY7VmPVGJS1vUwYc+2Q20dBes%2FanVwCUHNpFFcXWYM7xw5%2FRhIVF3hCnb+WTXyd4kai6Nv4StAsYWa4gD28XBBieVsDDfMaljBUAFNR%2F4GpRn5X8%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification</value>
      <webElementGuid>0e96539f-b2e9-4393-a337-c26471ed45a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Not now
                </value>
      <webElementGuid>4030f288-055c-4724-b22a-e75a677d5065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap-account-fixup-phone-skip-link&quot;)</value>
      <webElementGuid>0c77a188-2544-4614-95cf-d32df2b0b6ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ap-account-fixup-phone-skip-link']</value>
      <webElementGuid>b79dbf8b-b9fd-41d3-a17b-bf6c473175eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-account-fixup-phone-form']/div/div[5]/div/a</value>
      <webElementGuid>a5d92db4-6f6d-4d1d-9756-0befa2e15f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Not now')]</value>
      <webElementGuid>03b03ab4-ee12-4426-91ca-e8232b79b9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=XLvfZ7VC3EgHXkP4dIJ2Tj2BbyF1kj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_ya_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7Cax1j8TWvpt5B+nR5XQYnJTYJNOJu4tgl2mjSfMRaoY5ZjX%2FIzu6ZUl64qqjM08NKrKLv+tUYrtIiuSrQt3%2Fh+ZYIPa9c8TYpxtUNRU%2FANvlozPOkvu5FxVU+Sdhpv8P4AHOq3vCOxjxeh8GMeGf+BX2rjWiaUUD+Lk8Qg4USLT5rhqQlM9BXX8m4nKjSUB+7Fsd%2FPD7py%2FtXeUtT0G0yN5m6FROd+QGSsgj7HVNQY7VmPVGJS1vUwYc+2Q20dBes%2FanVwCUHNpFFcXWYM7xw5%2FRhIVF3hCnb+WTXyd4kai6Nv4StAsYWa4gD28XBBieVsDDfMaljBUAFNR%2F4GpRn5X8%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification')]</value>
      <webElementGuid>077650f9-02f7-4d1e-8dfc-befcacaefe04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>33ccfd6f-607d-4a2d-9150-d94daa0ebbc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ap-account-fixup-phone-skip-link' and @href = 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=XLvfZ7VC3EgHXkP4dIJ2Tj2BbyF1kj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_ya_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7Cax1j8TWvpt5B+nR5XQYnJTYJNOJu4tgl2mjSfMRaoY5ZjX%2FIzu6ZUl64qqjM08NKrKLv+tUYrtIiuSrQt3%2Fh+ZYIPa9c8TYpxtUNRU%2FANvlozPOkvu5FxVU+Sdhpv8P4AHOq3vCOxjxeh8GMeGf+BX2rjWiaUUD+Lk8Qg4USLT5rhqQlM9BXX8m4nKjSUB+7Fsd%2FPD7py%2FtXeUtT0G0yN5m6FROd+QGSsgj7HVNQY7VmPVGJS1vUwYc+2Q20dBes%2FanVwCUHNpFFcXWYM7xw5%2FRhIVF3hCnb+WTXyd4kai6Nv4StAsYWa4gD28XBBieVsDDfMaljBUAFNR%2F4GpRn5X8%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification' and (text() = '
                  Not now
                ' or . = '
                  Not now
                ')]</value>
      <webElementGuid>7288dfe3-a808-4c25-9375-898cd31715c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
