<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Apple iPhone15Pro Silicone Case with M_b2a162</name>
   <tag></tag>
   <elementGuidId>66c622d1-7838-4e0a-9f2a-02cfe92ee1db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8312bf5f-f0db-4560-84ea-e7a809743d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>12111f8f-9552-4e61-9964-019f158e2e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-large product-title-word-break</value>
      <webElementGuid>6bc3950b-c055-40b1-b1d2-e8037d4fe882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        Apple iPhone 15 Pro Silicone Case with MagSafe - Winter Blue ​​​​​​​       </value>
      <webElementGuid>66e313d5-1550-463d-bb4d-2a6c3181a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTitle&quot;)</value>
      <webElementGuid>9ddb0b3b-15b2-481d-af16-ab61a90f9938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>e4ed5e1d-e4cd-42e5-97bb-7689600d4b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>6af4c942-fde3-4e3b-b06e-c334ebee44ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>a6a7f88e-e9db-43f9-bf8b-c99b3d57680c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '        Apple iPhone 15 Pro Silicone Case with MagSafe - Winter Blue ​​​​​​​       ' or . = '        Apple iPhone 15 Pro Silicone Case with MagSafe - Winter Blue ​​​​​​​       ')]</value>
      <webElementGuid>3c9f6d3c-fd37-41a0-b1fb-ca8f7422adca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
