<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divnav-vsar-lens-container</name>
   <tag></tag>
   <elementGuidId>a4a3cf13-f64d-4303-b547-795664bc6225</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-vsar-lens-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-vsar-lens-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd9c6577-4ee6-4bc6-8125-dd94c158073d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-vsar-lens-container</value>
      <webElementGuid>a6011540-792a-4d82-abcd-8ce19e0b5024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-search-field</value>
      <webElementGuid>da9d4179-9b31-4458-aa56-9c22a67ec001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-vsar-lens-container&quot;)</value>
      <webElementGuid>0193ede1-db2d-4089-8158-25ab1eea6068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='nav-vsar-lens-container']</value>
      <webElementGuid>52954991-c862-4d29-adcf-0f8af96b4a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='nav-search-bar-form']/div[2]/div[3]</value>
      <webElementGuid>26cd4b30-2b14-46be-b027-81daf2e95251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]</value>
      <webElementGuid>96af58e8-2bf0-43ae-b4aa-5ced6606f96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'nav-vsar-lens-container']</value>
      <webElementGuid>88f72cc5-cd71-4c5b-bfc6-f4a908238213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
