<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.buy-now</name>
   <tag></tag>
   <elementGuidId>16ec96e3-f902-44e9-9189-da51e7434a22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buy-now-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buy-now-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bd9e8e3-154b-4e2a-b2f0-6113644e4ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buy-now-button</value>
      <webElementGuid>aed99469-eaaf-456e-808e-b4f035d0788f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.buy-now</value>
      <webElementGuid>8293a65b-0e84-4a61-9d49-0f2ee78246f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>6bf979ac-55b8-481b-8df3-d5f5465b26f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__</value>
      <webElementGuid>7633d29c-4335-4841-9677-1c45c3565279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>70948173-06d2-4b86-92aa-a7b4e92d162c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b43a8a8e-ffc2-47ba-a23d-03fd0b685237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.buy-now-announce</value>
      <webElementGuid>44a040ad-2a87-470d-a573-bba24cf7bf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-now-button&quot;)</value>
      <webElementGuid>553731d6-ca70-4ff9-bd12-0a17955def65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buy-now-button']</value>
      <webElementGuid>35158a44-3b68-4909-93b3-c598b64ce1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submit.buy-now']/span/input</value>
      <webElementGuid>a88a5046-a668-4ed6-9cfc-78e9f4993b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/input</value>
      <webElementGuid>d13de18c-7a5e-43d8-a57e-722fe7f4685d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buy-now-button' and @name = 'submit.buy-now' and @title = 'Buy Now' and @type = 'submit']</value>
      <webElementGuid>385f0bde-b091-43a2-8c35-6b5a0ad975be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
