<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Visit the Apple Store</name>
   <tag></tag>
   <elementGuidId>dfdd98c3-4869-4397-9795-88311163a05f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bylineInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bylineInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fdf4a3f1-e3ce-4e3a-ae5b-6525b0d3cd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bylineInfo</value>
      <webElementGuid>593958b7-9ce7-4e41-bbe6-50f5fcd1864a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>b715678b-64e2-416f-b028-ea229a3621c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/stores/Apple/page/77D9E1F7-0337-4282-9DB6-B6B8FB2DC98D?ref_=ast_bln</value>
      <webElementGuid>3d30d6bf-275a-49aa-b142-600f0b7d3b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visit the Apple Store</value>
      <webElementGuid>0e950e00-28d4-4c51-9af7-8b85bed257da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bylineInfo&quot;)</value>
      <webElementGuid>accd216d-ab81-46ab-9fcf-587846940f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bylineInfo']</value>
      <webElementGuid>71cf3899-aa22-45ae-8d33-fe130f62583f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bylineInfo_feature_div']/div/a</value>
      <webElementGuid>58980abf-c338-4be7-ac8e-715ea338ca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Visit the Apple Store')]</value>
      <webElementGuid>dedbfdfe-39a9-4dd4-ab31-6b69134cc5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/stores/Apple/page/77D9E1F7-0337-4282-9DB6-B6B8FB2DC98D?ref_=ast_bln')]</value>
      <webElementGuid>103fef1b-9318-4692-895f-43cd39fc312a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/div/a</value>
      <webElementGuid>e00b5db5-ed24-4309-862b-18b6ecf82d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bylineInfo' and @href = '/stores/Apple/page/77D9E1F7-0337-4282-9DB6-B6B8FB2DC98D?ref_=ast_bln' and (text() = 'Visit the Apple Store' or . = 'Visit the Apple Store')]</value>
      <webElementGuid>f87f78c3-89dc-4442-b42f-deb6622e45fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
