<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ship outside the US_1</name>
   <tag></tag>
   <elementGuidId>4e6940e7-aa33-41d0-a1bb-b5d327a4b4b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='GLUXCountryValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GLUXCountryValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a49ef43c-f5e9-413b-8713-2dd4bb84324d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-prompt</value>
      <webElementGuid>e0deed47-64f9-4c7b-8bcf-013f314b8f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GLUXCountryValue</value>
      <webElementGuid>e64f9911-5e52-44b3-9fc0-aefa9873c69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ship outside the US</value>
      <webElementGuid>35b2e433-a7eb-4b69-a248-eaacbdc2c00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GLUXCountryValue&quot;)</value>
      <webElementGuid>5a4a2ba5-d883-4797-ad37-43d89ad43ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='GLUXCountryValue']</value>
      <webElementGuid>8bdf164f-072d-4776-b434-a849a39b39f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='GLUXCountryListDropdown']/span/span/span</value>
      <webElementGuid>51ec02d5-6098-497a-a2d4-bfc2d02eac95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/span/span/span/span</value>
      <webElementGuid>1ddd760e-9821-447f-a7e7-39a8adbd90d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'GLUXCountryValue' and (text() = 'Ship outside the US' or . = 'Ship outside the US')]</value>
      <webElementGuid>05444605-8d14-4148-aa15-fa3e2a26ed0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
