<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_proceedToRetailCheckout</name>
   <tag></tag>
   <elementGuidId>23826170-bbf4-441d-81ab-d9bbf842567c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='proceedToRetailCheckout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;proceedToRetailCheckout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b2a7563-13ec-4b6c-9b5c-1d2bf771582f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proceedToRetailCheckout</value>
      <webElementGuid>859916d3-fd7f-46f0-b604-c7d3f315f4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feature-id</name>
      <type>Main</type>
      <value>proceed-to-checkout-action</value>
      <webElementGuid>76f34cdb-631f-4aed-8502-822ecf95ca8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>0b2cdf08-33d9-4ae2-a4f7-38dd2a14d5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>59f82f66-bdab-49e8-92fa-2211a13480f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed to checkout</value>
      <webElementGuid>60fe04b2-fdf3-423f-b107-b984aa5a14c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>sc-buy-box-ptc-button-announce</value>
      <webElementGuid>fc1ddf8e-132a-49a2-9970-fc96a47a7050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-ptc-button&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>5dd09f4e-2706-4109-b4b3-d31b9d3f7ff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='proceedToRetailCheckout']</value>
      <webElementGuid>db1aecd4-9d83-49ab-a4ed-0442b98145bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sc-buy-box-ptc-button']/span/input</value>
      <webElementGuid>9509247f-f03b-47ef-94c3-7cc2b81a8e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/span/span/span/input</value>
      <webElementGuid>a8d47db0-a43c-4088-9013-4fd22c19f69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'proceedToRetailCheckout' and @type = 'submit']</value>
      <webElementGuid>f05c9402-b17c-439e-ba77-c1ce97fefe66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
