<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_sc-product-image celwidget</name>
   <tag></tag>
   <elementGuidId>c67bd60a-2799-4a42-88fa-03b04e0d6ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sc-product-image.celwidget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-to-cart-confirmation-image']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>32a0b14d-294d-4ec2-a4c2-d89a68be1540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SAMSUNG Galaxy S23 FE Cell Phone, 128GB, Unlocked Android Smartphone, Long Battery Life, Premium Processor, Tough Gorilla Glass Display, Hi-Res 50MP Camera, US Version, 2023, Mint</value>
      <webElementGuid>71832d13-ff84-402e-99e3-6177cf0ab2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71JB7R7ttqL._AC_AA300_.jpg</value>
      <webElementGuid>bbb8a2a6-0c9d-4a2f-a9b2-2525de4838d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-product-image celwidget</value>
      <webElementGuid>364d0b45-3840-49f5-8d46-9707e3389fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>578390fa-3f4e-44af-a4da-b2ea405a8be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ddf17316-0c63-4080-955d-16d6cd58b485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-a-hires</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/71JB7R7ttqL._AC_AA300_.jpg</value>
      <webElementGuid>32119fb4-dc18-49d6-a940-8d48df97e04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>15onv3-etzfqi-dj9uke-vqlgj5</value>
      <webElementGuid>6ec14142-db22-4488-8e4d-fdb5ec4d7235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-confirmation-image&quot;)/div[1]/a[@class=&quot;a-link-normal sc-product-link&quot;]/img[@class=&quot;sc-product-image celwidget&quot;]</value>
      <webElementGuid>6fdd752e-60c6-4ea9-994d-fcd1039dddc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-to-cart-confirmation-image']/div/a/img</value>
      <webElementGuid>53570797-2de5-4b74-ac43-b7ec17acc381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='SAMSUNG Galaxy S23 FE Cell Phone, 128GB, Unlocked Android Smartphone, Long Battery Life, Premium Processor, Tough Gorilla Glass Display, Hi-Res 50MP Camera, US Version, 2023, Mint'])[3]</value>
      <webElementGuid>b91dd783-09f2-4c44-ad53-149fcc287048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/a/img</value>
      <webElementGuid>f01d0473-8d88-486d-aee0-e2eac3d6c9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'SAMSUNG Galaxy S23 FE Cell Phone, 128GB, Unlocked Android Smartphone, Long Battery Life, Premium Processor, Tough Gorilla Glass Display, Hi-Res 50MP Camera, US Version, 2023, Mint' and @src = 'https://m.media-amazon.com/images/I/71JB7R7ttqL._AC_AA300_.jpg']</value>
      <webElementGuid>6062f216-6517-45cd-9338-bff747ff522c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
