<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput-box-otp</name>
   <tag></tag>
   <elementGuidId>a0fa9e1d-19c4-41ec-9841-9eb26f6368a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-box-otp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-box-otp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca185edd-a517-4ccb-93be-c564e68f3cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>80c87f40-ca02-442e-ba96-e864081431b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2b39373f-e2ca-4a45-a050-2af2517aad90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-box-otp</value>
      <webElementGuid>d48e04b1-9fb7-4dfb-bcec-5bdd796d786b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b3a2f72-280f-4557-9930-d39b126f4337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ffe9d288-8cc1-400c-b9a9-b28705786f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text cvf-widget-input cvf-widget-input-code single-input-box-otp</value>
      <webElementGuid>84ef7d1e-9958-42fd-b7b8-70b84c1dc38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-box-otp&quot;)</value>
      <webElementGuid>212e9a78-1ce9-4216-a041-08dbd10337c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-box-otp']</value>
      <webElementGuid>2725492e-7f4b-4965-b478-556a9618976a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-input-code']/span/div/input</value>
      <webElementGuid>f634b3b1-752b-4430-a243-84c92a03bfa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ff7890b4-91f7-4a92-85b9-26b4e5c3b14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'input-box-otp']</value>
      <webElementGuid>4987c399-1a8e-4a48-94b4-9747769e935a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
