<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_a-icon a-logo</name>
   <tag></tag>
   <elementGuidId>33832e10-c9fe-418b-ae98-90a193535781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0c1c82db-96a4-4dd1-9f3a-62f80cd9623e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-logo</value>
      <webElementGuid>cf2f10dc-883c-427f-a8f9-4022ac837319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;a-no-js&quot;]/body[1]/div[@class=&quot;a-container a-padding-double-large&quot;]/div[@class=&quot;a-row a-spacing-double-large&quot;]/div[@class=&quot;a-row a-spacing-medium a-text-center&quot;]/i[@class=&quot;a-icon a-logo&quot;]</value>
      <webElementGuid>124b38e1-65ab-43c3-bf73-c236fc2299d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>2168980c-b04c-4757-8b97-023f4b2ba617</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
