<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Not now</name>
   <tag></tag>
   <elementGuidId>fc601a62-ca13-4fe0-ad55-2c827a2f90e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ap-account-fixup-phone-skip-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ap-account-fixup-phone-skip-link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21f9e540-2fbf-4587-80da-27adf0074610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ap-account-fixup-phone-skip-link</value>
      <webElementGuid>227a9bf9-ce43-4d24-88b6-a21e9329fd23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>fff33cb0-46db-4b97-9144-ec560ca39c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=dhE9Xk3Q4jzj2BOWlwik27AXCGD5sj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7C8a%2F0eeTZL12prPd+klxJfRdEZjLMPtBZS+uQ3sjaTtMqjytZwR7HRajo3FltySwd41lvJOowaKRWzOEHB%2F1zNH0JlMgriHRAwIc1x7SO0OeCoQ+sAlGokti28vo504DMAk4KpX%2FNDi5pk7tgeo0lcjrQOd3WgjJ4J0vma1+1JMUo7lWxtZUfYi3lBtipY%2F28fVrSbJdyiWdBxILJS81TBWdzYyzskO%2FQ1ZMA3yjRjFLQ7r4XKlUpmaanDEgJtcrhGt9on%2Fn74LTwP%2F%2FaUiqC8kKmk7eh4clqjZPcvmYDx3+jDZkLjCf7FHPV%2FhTZhQVd%2FstQDXpmldWPL9PTn6GDhA%3D%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification</value>
      <webElementGuid>2a924347-5423-4793-a03f-ae8e82c90f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  Not now
                </value>
      <webElementGuid>96240196-09e4-4223-99e3-2288ec06ea04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap-account-fixup-phone-skip-link&quot;)</value>
      <webElementGuid>2a4bddec-34ba-4c42-8e7b-3682f7827c7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ap-account-fixup-phone-skip-link']</value>
      <webElementGuid>a05be676-7f29-44c0-b118-79d89fc83220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='auth-account-fixup-phone-form']/div/div[5]/div/a</value>
      <webElementGuid>361f9363-612c-4920-8251-f6c076403578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Not now')]</value>
      <webElementGuid>20aeff5b-0a88-48c3-8c97-a7d302c316e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=dhE9Xk3Q4jzj2BOWlwik27AXCGD5sj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7C8a%2F0eeTZL12prPd+klxJfRdEZjLMPtBZS+uQ3sjaTtMqjytZwR7HRajo3FltySwd41lvJOowaKRWzOEHB%2F1zNH0JlMgriHRAwIc1x7SO0OeCoQ+sAlGokti28vo504DMAk4KpX%2FNDi5pk7tgeo0lcjrQOd3WgjJ4J0vma1+1JMUo7lWxtZUfYi3lBtipY%2F28fVrSbJdyiWdBxILJS81TBWdzYyzskO%2FQ1ZMA3yjRjFLQ7r4XKlUpmaanDEgJtcrhGt9on%2Fn74LTwP%2F%2FaUiqC8kKmk7eh4clqjZPcvmYDx3+jDZkLjCf7FHPV%2FhTZhQVd%2FstQDXpmldWPL9PTn6GDhA%3D%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification')]</value>
      <webElementGuid>9a5e9024-5410-4984-a321-9f68252e52fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>042057ac-39e7-4e68-8f1d-3d5b540985a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ap-account-fixup-phone-skip-link' and @href = 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=900&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;appActionToken=dhE9Xk3Q4jzj2BOWlwik27AXCGD5sj3D&amp;pageId=usflex&amp;openid.pape.preferred_auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&amp;openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin%26returnFromLogin%3D1&amp;openid.assoc_handle=usflex&amp;partialToken=PT%7C1%7C8a%2F0eeTZL12prPd+klxJfRdEZjLMPtBZS+uQ3sjaTtMqjytZwR7HRajo3FltySwd41lvJOowaKRWzOEHB%2F1zNH0JlMgriHRAwIc1x7SO0OeCoQ+sAlGokti28vo504DMAk4KpX%2FNDi5pk7tgeo0lcjrQOd3WgjJ4J0vma1+1JMUo7lWxtZUfYi3lBtipY%2F28fVrSbJdyiWdBxILJS81TBWdzYyzskO%2FQ1ZMA3yjRjFLQ7r4XKlUpmaanDEgJtcrhGt9on%2Fn74LTwP%2F%2FaUiqC8kKmk7eh4clqjZPcvmYDx3+jDZkLjCf7FHPV%2FhTZhQVd%2FstQDXpmldWPL9PTn6GDhA%3D%3D&amp;openid.mode=checkid_setup&amp;appAction=ACCOUNT_FIXUP_PHONE_ADD_COMPLETE&amp;ref_=ap_reachability_skip&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;authenticationPolicy=SinglefactorWithMobileVerification' and (text() = '
                  Not now
                ' or . = '
                  Not now
                ')]</value>
      <webElementGuid>45d84ff1-1570-481b-950b-1789c9d07fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
