<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overlay__overlay__LloCU EditorialTile__ov_b1d8ad</name>
   <tag></tag>
   <elementGuidId>c3b28b5f-bdb7-4f9f-b68b-a82da296e2d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#blstsrmxko > div.EditorialTile__container__MuV7R > div.EditorialTile__content__Ey9JH > div.EditorialTile__innerContent__n92i8 > a.Overlay__overlay__LloCU.EditorialTile__overlay__RMD1L</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='blstsrmxko']/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f6b57fe1-9aef-4ca5-9017-f528e855e155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/stores/page/C565BEA8-F3D9-4C1B-8372-85D2A87F2F60?ingress=2&amp;visitId=8d0e2060-ad7a-4c82-8a83-6c811a34e27b&amp;ref_=ast_bln</value>
      <webElementGuid>69f880b1-0e3e-4b2d-8b46-f7dc38ceb2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Overlay__overlay__LloCU EditorialTile__overlay__RMD1L</value>
      <webElementGuid>21214012-1fb2-4297-af20-e00e924e1a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blstsrmxko&quot;)/div[@class=&quot;EditorialTile__container__MuV7R&quot;]/div[@class=&quot;EditorialTile__content__Ey9JH&quot;]/div[@class=&quot;EditorialTile__innerContent__n92i8&quot;]/a[@class=&quot;Overlay__overlay__LloCU EditorialTile__overlay__RMD1L&quot;]</value>
      <webElementGuid>6b196774-48bc-4cfa-afbb-4a22aa16f601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blstsrmxko']/div/div/div/a</value>
      <webElementGuid>4fe7202a-aaac-4d32-9de1-0d549831fee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/stores/page/C565BEA8-F3D9-4C1B-8372-85D2A87F2F60?ingress=2&amp;visitId=8d0e2060-ad7a-4c82-8a83-6c811a34e27b&amp;ref_=ast_bln')])[3]</value>
      <webElementGuid>f8c3ae7e-bc97-4ec5-8c43-6be2c23f1736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div/a</value>
      <webElementGuid>89ea66a5-35d6-40d3-bd01-4961edcfe1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/stores/page/C565BEA8-F3D9-4C1B-8372-85D2A87F2F60?ingress=2&amp;visitId=8d0e2060-ad7a-4c82-8a83-6c811a34e27b&amp;ref_=ast_bln']</value>
      <webElementGuid>6a42688b-82b9-4dd3-9db0-6089a962adb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
