<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_English</name>
   <tag></tag>
   <elementGuidId>88de52e4-df37-4bcd-ac10-50bdde2afdb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#icp-touch-link-language</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-touch-link-language']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ccc49ec8-a265-43a8-8cd2-50d6643f6905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/customer-preferences/edit?ie=UTF8&amp;preferencesReturnUrl=%2F%3Fref_%3Dnav_ya_signin&amp;ref_=footer_lang</value>
      <webElementGuid>1427a5a9-ea0e-44bd-92c3-a0e74a9b3e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Choose a language for shopping.</value>
      <webElementGuid>fb6b6a31-4285-4d65-b147-ed5793fe2d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icp-button nav-active</value>
      <webElementGuid>90b4289b-b865-4c7b-8997-6548fefbf4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-touch-link-language</value>
      <webElementGuid>0278610b-ac31-4686-a316-50c9b092ba92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  English
</value>
      <webElementGuid>1b437ae1-2b70-4e55-976c-6eca77194d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-touch-link-language&quot;)</value>
      <webElementGuid>20eb7a78-1bf2-49bc-bd6f-14f76908ed2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-touch-link-language']</value>
      <webElementGuid>1ee07d1a-3727-46d2-976e-5d8d5ae8a954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navFooter']/div[3]/span[2]/div/a</value>
      <webElementGuid>3709e853-08a7-4c0f-b6d9-de0ee1a40658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/customer-preferences/edit?ie=UTF8&amp;preferencesReturnUrl=%2F%3Fref_%3Dnav_ya_signin&amp;ref_=footer_lang')]</value>
      <webElementGuid>29ee6001-4c4f-4689-aa35-b074bdac5db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/a</value>
      <webElementGuid>d6958e91-4269-4060-b517-5b1243622759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/customer-preferences/edit?ie=UTF8&amp;preferencesReturnUrl=%2F%3Fref_%3Dnav_ya_signin&amp;ref_=footer_lang' and @id = 'icp-touch-link-language' and (text() = '
  English
' or . = '
  English
')]</value>
      <webElementGuid>65c67a80-d4d6-410c-9dee-18b1c37942da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
